---
- name: Install Monitoring
  connection: local  
  hosts: localhost
  become: true
  become_user: root
  tasks:
    - name: Install helm if not exists
      unarchive:
        src: https://get.helm.sh/helm-v3.13.0-linux-amd64.tar.gz
        dest: /usr/local/bin
        extra_opts: "--strip-components=1"
        owner: root
        group: root
        mode: 0755
        remote_src: true
      args:
        creates: /usr/local/bin/helm
    - name: Deploy Manifests
      command: k0s kubectl apply -f kubernetes
    - name: Add repo
      command: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      environment:
        KUBECONFIG: /var/lib/k0s/pki/admin.conf
    - name: Update
      command: helm repo update
      environment:
        KUBECONFIG: /var/lib/k0s/pki/admin.conf
    - name: Install Monitoring
      command: helm upgrade -i --values values.yaml monitoring prometheus-community/kube-prometheus-stack -n monitoring 
      environment:
        KUBECONFIG: /var/lib/k0s/pki/admin.conf
    
      